[package]
name = "reflect_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = {version = "2.0.22", features = ["extra-traits"] }
quote = "1.0.9"

[lib]
proc-macro = true
