[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[lib]
name = "sandbox"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
engine = { path = "../engine" }
serde.workspace = true
