[package]
name = "engine_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.69"
syn = { version = "2.0.38", features = ["full", "extra-traits"] }
quote = "1.0.33"
uuid = "1.5"
sha-1 = "0.10"

[lib]
proc-macro = true