[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
assets_manager = "0.10.2"
bytemuck = "1.13.1"
eframe = "0.22.0"
egui = "0.22.0"
egui-wgpu = "0.22.0"
egui_dock = "0.6.3"
enum-map = "2.6.1"
lazy_static = "1.4.0"
log = "0.4.19"
serde = "1.0.182"
uuid = "1.4.1"
specs = "0.19.0"
nalgebra-glm = { version= "0.18.0", features = ["serde-serialize"] }
indextree = "4.6.0"
russimp = "2.0.5"
impls = "1.0.3"

[features]
default = ["eframe/wgpu", "assets_manager/ron"]
