[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.13.1"
eframe = { version = "0.22.0", features = ["wgpu"] }
egui = "0.22.0"
egui-wgpu = "0.22.0"
egui_dock = "0.6.3"
enum-map = "2.6.1"
lazy_static = "1.4.0"
log = "0.4.19"
serde = "1.0.182"
uuid = { version = "1.4.1", features = ["v4"] }
nalgebra-glm = { version = "0.18.0", features = ["serde-serialize"] }
indextree = "4.6.0"
russimp = "2.0.5"
notify = "6.0.1"
specs = "0.19.0"
inventory = "0.3.11"
