[package]
name = "launcher"
authors = ["Ruben <ruben.e.sanchez.a@gmail.com>", "Cristian"]
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.22.0", features = ["wgpu"] }
egui = "0.22.0"