[package]
name = "project"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
toml.workspace = true
tinytemplate.workspace = true
serde.workspace = true
chrono.workspace = true
