[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[features]
default = []
syntax_highlighting = ["syntect"]

[dependencies]
engine = { path = "../engine" }
enum-map = "2.6.1"
syntect = { version = "5", optional = true, default-features = false, features = [
    "default-fancy",
] }
