[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "editor"
path = "src/main.rs"

[features]
default = []

[dependencies]
engine = { path = "../engine" }
project = { path = "../project" }
bytemuck = "1.14.0"
lazy_static = "1.4.0"
serde = "1.0.189"
inventory = "0.3.12"
egui-gizmo = "0.16.0"
num = "0.4.1"
num-derive = "0.4.1"
num-traits = "0.2.17"
sharedlib = "7.0.0"
convert_case = "0.6.0"
rfd = "0.14.1"
