[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[features]
default = []
syntax_highlighting = ["syntect"]

[dependencies]
assets_manager = "0.10.2"
bytemuck = "1.13.1"
engine = { path = "../engine" }
project = { path = "../project" }
enum-map = "2.6.1"
lazy_static = "1.4.0"
serde = "1.0.182"
syntect = { version = "5", optional = true, default-features = false, features = [
    "default-fancy",
] }
utils = { path = "../utils" }
reflect = { path = "../reflect" }
inventory = "0.3.11"
egui-gizmo = "0.11.0"
num = "0.4.1"
num-derive = "0.4.0"
num-traits = "0.2.16"
sharedlib = "7.0.0"
