[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[features]
default = []

serde = ["egui/serde", "dep:serde"]
syntax_highlighting = ["syntect"]

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"
egui_glow = "0.22.0"
egui_dock = "0.6.3"
engine = { path = "../engine" }
serde = { version = "1", optional = true, features = ["derive"] }
syntect = { version = "5", optional = true, default-features = false, features = [
    "default-fancy",
] }
enum-map = { version = "2", features = ["serde"] }
