[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Cprefer-dynamic", "-Zshare-generics=n", "-Cdebug-assertions=n"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clink-arg=-Wl,--undefined-version"]
