pub extern crate uuid;
pub extern crate eframe;
pub extern crate egui;
pub extern crate egui_dock;
pub extern crate egui_wgpu;
pub extern crate indextree;
pub extern crate inventory;
pub extern crate nalgebra_glm as glm;
pub extern crate russimp;
pub extern crate serde;
pub extern crate specs;
extern crate bevy_reflect;

pub mod utils;
pub mod assets;
pub mod core;
pub mod ecs;
pub mod math;
pub mod scene;
pub mod render;
pub mod type_registry;
