pub extern crate uuid;
pub extern crate eframe;
pub extern crate egui;
pub extern crate egui_dock;
pub extern crate egui_wgpu;
pub extern crate indextree;
pub extern crate inventory;
pub extern crate nalgebra_glm as glm;
pub extern crate reflect;
pub extern crate russimp;
pub extern crate serde;
pub extern crate specs;

pub mod assets;
pub mod core;
pub mod component;
pub mod math;
pub mod scene;
pub mod render;
pub mod net;