name: Cargo Test

on:
  pull_request:
  push:
    branches:
      - main
      - staging
      - "feature/**"
      - "fix/**"

jobs:
  engine-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: Run engine cargo tests
        run: cargo test -p engine --lib --tests
